dataset:
  data_path:
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic1.bed', 0]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic2.bed', 1]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic3.bed', 2]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic4.bed', 3]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic5.bed', 4]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic6.bed', 5]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic7.bed', 6]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic8.bed', 7]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic9.bed', 8]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic10.bed', 9]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic11.bed', 10]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic12.bed', 11]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic13.bed', 12]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic14.bed', 13]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic15.bed', 14]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic16.bed', 15]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic17.bed', 16]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic18.bed', 17]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic19.bed', 18]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic20.bed', 19]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic21.bed', 20]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic22.bed', 21]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic23.bed', 22]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic24.bed', 23]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic25.bed', 24]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic26.bed', 25]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic27.bed', 26]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic28.bed', 27]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic29.bed', 28]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic30.bed', 29]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic31.bed', 30]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic32.bed', 31]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic33.bed', 32]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic34.bed', 33]
    - ['data/CTdnsmpl_catlas_35_Topics_top_3k/bed/Topic35.bed', 34]
  genome_fasta: 'data/resources/mm10.fa'
  chrom_sizes: 'data/resources/mm10.chrom.sizes'
  out_dir: 'data/CTdnsmpl_catlas_35_Topics_top_3k'
  out_fn: 'regions_and_topics.bed'