name: "pb_ctdnsmpl"
tmp_dir: '/tmp'
dataset:
  genome_fasta: 'data/resources/mm10.fa'
  chrom_sizes: 'data/resources/mm10.chrom.sizes'
  out_dir: 'data/PB_CTdnsmpl_catlas_25_Topics_top_3k'
  out_fn: 'regions_and_topics.bed'
  bed_file:
  train_ratio: 0.6
  val_ratio: 0.2
  random_seed: 42
  augment: True
  augment_kwargs:
    random_shift: True
    augment_multiplier: 2
    extension: 50
    rc_prob: 0.3
  data_path:
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic1.bed', 0]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic2.bed', 1]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic3.bed', 2]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic4.bed', 3]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic5.bed', 4]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic6.bed', 5]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic7.bed', 6]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic8.bed', 7]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic9.bed', 8]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic10.bed', 9]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic11.bed', 10]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic12.bed', 11]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic13.bed', 12]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic14.bed', 13]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic15.bed', 14]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic16.bed', 15]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic17.bed', 16]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic18.bed', 17]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic19.bed', 18]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic20.bed', 19]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic21.bed', 20]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic22.bed', 21]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic23.bed', 22]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic24.bed', 23]
    - ['data/PB_CTdnsmpl_catlas_25_Topics_top_3k/bed/Topic25.bed', 24]
train:
  model: 'DeepMSN'
  lr_init: 3e-4
  decay_rate: 0.333
  weight_decay: 1e-2
  batch_size: 64
  epochs: 200
  num_workers: 1
  save_every_n_epochs: 50
  resume_from_checkpoint: False
  checkpoint:
    path: 
    resume_from_epoch: 50