name: "ctdnsmpl"
tmp_dir: '/tmp'
dataset:
  data_path:
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic1.bed', 0]
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic2.bed', 1]
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic3.bed', 2]
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic4.bed', 3]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic5.bed', 0]
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic6.bed', 5]
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic7.bed', 6]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic8.bed', 1]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic9.bed', 2]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic10.bed', 3]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic11.bed', 4]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic12.bed', 5]
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic13.bed', 12]
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic14.bed', 13]
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic15.bed', 14]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic16.bed', 6]
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic17.bed', 16]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic18.bed', 7]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic19.bed', 8]
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic20.bed', 19]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic21.bed', 9]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic22.bed', 10]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic23.bed', 11]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic24.bed', 12]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic25.bed', 13]
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic26.bed', 25]
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic27.bed', 26]
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic28.bed', 27]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic29.bed', 14]
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic30.bed', 29]
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic31.bed', 30]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic32.bed', 15]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic33.bed', 16]
    - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic34.bed', 17]
    # - ['data/CTdnsmpl_catlas_35_Topics_top_500/bed/Topic35.bed', 34]
  genome_fasta: 'data/resources/mm10.fa'
  chrom_sizes: 'data/resources/mm10.chrom.sizes'
  out_dir: 'data/CTdnsmpl_catlas_35_Topics_top_500'
  out_fn: 'regions_and_topics.bed'
train:
  model: 'DeepFlyBrain'
  lr_init: 1e-3
  weight_decay: 1e-2
  batch_size: 64
  epochs: 200
  num_workers: 1
  resume_from_checkpoint: False
  checkpoint:
    path: 
    resume_from_epoch: 200